export const DEFAULT_EXTENSIONS = [
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mts",
  ".mjs",
  ".cts",
  ".cjs",
  ".mdx",
  ".astro",
  ".graphql",
  ".gql",
  ".css",
  ".scss",
  ".vue",
  ".svelte",
];

export const HIDDEN_DIRECTORY_ALLOWLIST = [
  ".storybook",
  ".vitepress",
  ".well-known",
  ".changeset",
  ".github",
  ".client",
  ".server",
];

export const DEFAULT_IGNORE_PATTERNS = [
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/.git/**",
  "**/coverage/**",
  "**/*.d.ts",
  "**/*.min.js",
  "**/*.min.mjs",
  "**/mockServiceWorker.js",
];

export const SCRIPT_FILE_PATTERN = /(?:^|\s)(?:node|tsx|ts-node|tsc|npx|bun|esr|esno|jiti|babel-node)\s+(?:(?:-[\w-]+(?:\s+[\w./@-]+)?\s+)|(?:[\w/-]+\s+))*([\w./@-]+\.(?:ts|tsx|js|jsx|mts|mjs|cts|cjs))(?:\s|$)/;

export const SCRIPT_CONFIG_FILE_PATTERN = /--config\s+([\w./@-]+\.(?:ts|tsx|js|jsx|mts|mjs|cts|cjs))/;

export const SCRIPT_ENTRY_PATTERNS = [
  "bin/*.{ts,tsx,js,jsx,mts,mjs,cjs}",
];

export const DEFAULT_ENTRY_PATTERNS = [
  "src/index.{ts,tsx,js,jsx}",
  "src/main.{ts,tsx,js,jsx}",
  "index.{ts,tsx,js,jsx}",
  "main.{ts,tsx,js,jsx}",
];

export const CONFIG_FILE_PREFIXES = [
  "babel.config.",
  "rollup.config.",
  "webpack.config.",
  "postcss.config.",
  "stencil.config.",
  "remotion.config.",
  "metro.config.",
  "tsup.config.",
  "unbuild.config.",
  "esbuild.config.",
  "swc.config.",
  "turbo.",
  "jest.config.",
  "jest.setup.",
  "vitest.config.",
  "vitest.ci.config.",
  "vitest.setup.",
  "vitest.workspace.",
  "playwright.config.",
  "cypress.config.",
  "karma.conf.",
  "eslint.config.",
  "prettier.config.",
  "stylelint.config.",
  "lint-staged.config.",
  "commitlint.config.",
  "next.config.",
  "next-sitemap.config.",
  "nuxt.config.",
  "astro.config.",
  "sanity.config.",
  "sanity.cli.",
  "vite.config.",
  "tailwind.config.",
  "drizzle.config.",
  "knexfile.",
  "sentry.client.config.",
  "sentry.server.config.",
  "sentry.edge.config.",
  "react-router.config.",
  "typedoc.",
  "knip.config.",
  "fallow.config.",
  "i18next-parser.config.",
  "codegen.config.",
  "graphql.config.",
  "npmpackagejsonlint.config.",
  "release-it.",
  "release.config.",
  "contentlayer.config.",
  "next-env.d.",
  "env.d.",
  "vite-env.d.",
  "svelte.config.",
  "trigger.config.",
  "lage.config.",
];

export const ALWAYS_USED_PACKAGES = new Set([
  "typescript",
  "@types/node",
  "@types/react",
  "@types/react-dom",
  "eslint",
  "prettier",
  "husky",
  "lint-staged",
  "tslib",
]);

export const BUILTIN_MODULES = new Set([
  "assert",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "diagnostics_channel",
  "dns",
  "domain",
  "events",
  "fs",
  "http",
  "http2",
  "https",
  "inspector",
  "module",
  "net",
  "os",
  "path",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "repl",
  "stream",
  "string_decoder",
  "sys",
  "timers",
  "tls",
  "trace_events",
  "tty",
  "url",
  "util",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "zlib",
]);

export const PLATFORM_SUFFIXES = [".web", ".native", ".ios", ".android", ".desktop", ".windows", ".macos", ".any"];

export const REACT_NATIVE_PLATFORM_EXTENSIONS = [
  ".web.ts", ".web.tsx", ".web.js", ".web.jsx",
  ".native.ts", ".native.tsx", ".native.js", ".native.jsx",
  ".ios.ts", ".ios.tsx", ".ios.js", ".ios.jsx",
  ".android.ts", ".android.tsx", ".android.js", ".android.jsx",
];

export const RESOLVER_EXTENSIONS = [
  ...DEFAULT_EXTENSIONS,
  ".json",
  ".node",
  ".css",
  ".scss",
  ".less",
  ".svg",
  ".png",
  ".jpg",
  ".graphql",
  ".gql",
];

export const SHALLOW_WORKSPACE_MAX_DEPTH = 2;
